### ISSUE TITLE
Window Growing Bug

### ISSUE THREAD

**Issue by karakramer** [WeakAuras/WeakAuras-Companion#107] opened 2019-02-21 23:26 UTC
**Operating System:**
- [x] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
v1.1.5.
```

**Companion App Console Log:**
```
updaterHandler: checkForUpdates - {"updateInfo":{"files":[{"sha512":"+MmFW5KxcRqbZc9YrRoPyGjEDwWzGMak+HDjBfSLnr3/l7ut3TUk5IssQLtNrSNRl4sWvQf0361hTrhagCDUbQ==","size":45913752,"url":"weakauras-companion-setup-1.1.5.exe"}],"path":"weakauras-companion-setup-1.1.5.exe","releaseDate":"2019-01-31T18:45:39.022Z","releaseName":"1.1.5","releaseNotes":"<h3>Fix</h3>\n<ul>\n<li>error in multiline toasts</li>\n</ul>\n<h3>Known Issues</h3>\n<ul>\n<li>Mac : App is not signed by Apple and will give a link for manual update</li>\n<li>Updating Companion remove pinned link from windows taskbar</li>\n</ul>","sha512":"+MmFW5KxcRqbZc9YrRoPyGjEDwWzGMak+HDjBfSLnr3/l7ut3TUk5IssQLtNrSNRl4sWvQf0361hTrhagCDUbQ==","version":"1.1.5"},"versionInfo":{"files":[{"sha512":"+MmFW5KxcRqbZc9YrRoPyGjEDwWzGMak+HDjBfSLnr3/l7ut3TUk5IssQLtNrSNRl4sWvQf0361hTrhagCDUbQ==","size":45913752,"url":"weakauras-companion-setup-1.1.5.exe"}],"path":"weakauras-companion-setup-1.1.5.exe","releaseDate":"2019-01-31T18:45:39.022Z","releaseName":"1.1.5","releaseNotes":"<h3>Fix</h3>\n<ul>\n<li>error in multiline toasts</li>\n</ul>\n<h3>Known Issues</h3>\n<ul>\n<li>Mac : App is not signed by Apple and will give a link for manual update</li>\n<li>Updating Companion remove pinned link from windows taskbar</li>\n</ul>","sha512":"+MmFW5KxcRqbZc9YrRoPyGjEDwWzGMak+HDjBfSLnr3/l7ut3TUk5IssQLtNrSNRl4sWvQf0361hTrhagCDUbQ==","version":"1.1.5"}}
﻿
```

**WeakAuras Version:**
```
/run print(WeakAuras.versionString) in-game.
```

**WeakAuras Errors:**
```
1. Install https://mods.curse.com/addons/wow/BugSack
2. Install https://mods.curse.com/addons/wow/bug-grabber
3. Try to do whatever it is you're having a problem with again
4. Check your minimap for an icon that looks like a bag.  Is it green, or is it red?
   • GREEN
      • WeakAuras is working correctly.
      • Either you found a behavioral bug, or you are just doing it wrong :)
      • Explain the steps you took, and we will try to figure out what happened.
   • RED 
     • There are error messages. Click on the red bag to see them.
     • Copy & Paste here all of the error messages (there may be more than one, click the 'previous' button on the dialog to see previous ones
```

**Describe the bug**
When clicking near the top of the window, the window begins growing, this even occurs while moving the window

**To Reproduce**
Go to Main and click about 10 pixels right and 5 pixels north of the last "N" in "Companion"
VIDEO OF BUG INCLUDED

**Expected behavior**

**Screenshots**
https://www.twitch.tv/videos/384541860
Full length:
https://www.twitch.tv/videos/384536694##

**Comment by mrbuds** [comment] 2019-02-22 00:10
Can't reproduce, you didn't tell (as asked by the form) which version of Companion do you use

**Comment by karakramer** [comment] 2019-02-22 00:13
Version 1.1.5

**Comment by crisin** [comment] 2019-03-12 17:51
Can reproduce with version 1.1.7 on windows 10. clicking and holding makes the window grow until it reaches fullscreen resolution.

**Comment by mrbuds** [comment] 2019-06-01 12:30
fixed with https://github.com/WeakAuras/WeakAuras-Companion/commit/2f01eb9bb35edfdefa9a4995ff68d7ec86855372

**Closed by mrbuds** 2019-06-01 12:30 UTC
Labels: bug
