### ISSUE TITLE
Lua error when trying to update an aura that was previously part of a group

### ISSUE THREAD

**Issue by Pewtro** [WeakAuras/WeakAuras-Companion#68] opened 2019-01-14 17:04 UTC
**Operating System:**
- [x] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
1.0.18
```

**Companion App Console Log:**

**WeakAuras Version:**
```
2.11.0
```

**WeakAuras Errors:**

```

1x WeakAuras\Transmission.lua:1207: attempt to get length of field 'controlledChildren' (a nil value)
WeakAuras\Transmission.lua:1207: in function `MatchInfo'
WeakAuras\Transmission.lua:1727: in function `Import'
...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:759: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:756>

Locals:
data = <table> {
 grow = "RIGHT"
 controlledChildren = <table> {
 }
 xOffset = -479.000092
 yOffset = -29.998810
 sortHybridTable = <table> {
 }
 space = 2
 url = "https://wago.io/ByyBK8vpG/33"
 actions = <table> {
 }
 triggers = <table> {
 }
 radius = 200
 selfPoint = "LEFT"
 align = "CENTER"
 desc = "Reloe#1399 on Discord"
 rotation = 0
 version = 33
 load = <table> {
 }
 animate = false
 scale = 1
 border = "None"
 regionType = "dynamicgroup"
 hybridPosition = "hybridFirst"
 sort = "hybrid"
 animation = <table> {
 }
 hybridSortMode = "ascending"
 constantFactor = "RADIUS"
 authorOptions = <table> {
 }
 borderOffset = 16
 semver = "1.0.0-33"
 config = <table> {
 }
 id = "T22 Uldir Raid"
 background = "None"
 frameStrata = 1
 anchorFrameType = "SCREEN"
 backgroundInset = 0
 uid = "5E(za9QWoWD"
 stagger = 0
 expanded = true
 conditions = <table> {
 }
 internalVersion = 11
 anchorPoint = "CENTER"
}
children = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
 53 = <table> {
 }
 54 = <table> {
 }
 55 = <table> {
 }
 56 = <table> {
 }
 57 = <table> {
 }
 58 = <table> {
 }
 59 = <table> {
 }
 60 = <table> {
 }
 61 = <table> {
 }
 62 = <table> {
 }
 63 = <table> {
 }
 64 = <table> {
 }
 65 = <table> {
 }
 66 = <table> {
 }
 67 = <table> {
 }
 68 = <table> {
 }
 69 = <table> {
 }
 70 = <table> {
 }
 71 = <table> {
 }
 72 = <table> {
 }
 73 = <table> {
 }
 74 = <table> {
 }
 75 = <table> {
 }
 76 = <table> {
 }
 77 = <table> {
 }
 78 = <table> {
 }
 79 = <table> {
 }
 80 = <table> {
 }
 81 = <table> {
 }
 82 = <table> {
 }
 83 = <table> {
 }
 84 = <table> {
 }
 85 = <table> {
 }
}
target = <table> {
 textFlags = "None"
 stacksSize = 12
 xOffset = 4.000183
 stacksFlags = "None"
 yOffset = 248.999939
 anchorPoint = "CENTER"
 borderColor = <table> {
 }
 url = "https://wago.io/ByyBK8vpG/32"
 icon = false
 fontFlags = "OUTLINE"
 icon_color = <table> {
 }
 selfPoint = "CENTER"
 barColor = <table> {
 }
 desaturate = false
 sparkOffsetY = 0
 load = <table> {
 }
 timerColor = <table> {
 }
 useAdjustededMin = false
 regionType = "aurabar"
 stacks = false
 texture = "Minimalist"
 textFont = "Expressway"
 sparkTexture = "WeakAuras\Media\Textures\Square_White"
 spark = false
 timerFont = "Expressway"
 alpha = 1
 borderInset = 11
 textColor = <table> {
 }
 borderBackdrop = "Blizzard Tooltip"
 customTextUpdate = "update"
 displayTextLeft = " "
 triggers = <table> {
 }
 internalVersion = 11
 animation = <table> {
 }
 backdropInFront = false
 text = true
 sparkRotation = 0
 stickyDuration = false
 sparkRotationMode = "AUTO"
 sparkWidth = 2
 version = 32
 backgroundColor = <table> {
 }
 height = 39.999969
 timerFlags = "None"
 textSize = 20
 sparkBlendMode = "ADD"
 useAdjustededMax = false
 borderOffset = 5
 sparkOffsetX = 0
 backdropColor = <table> {
 }
 width = 184.000183
 zoom = 0
 border = false
 borderEdge = "None"
 rotateText = "NONE"
 borderInFront = true
 id = "Ghuun Dance Timer"
 icon_side = "RIGHT"
 actions = <table> {
 }
 displayTextRight = "%p Dance"
 sparkHeight = 27
 stacksFont = "Friz Quadrata TT"
 borderSize = 16
 stacksColor = <table> {
 }
 timerSize = 12
 timer = true
 sparkHidden = "NEVER

```

**Describe the bug**

**To Reproduce**

**Expected behavior**

Expect it to update the single aura that was extracted from the larger group. 

**Screenshots**

**Include a .zip file containing:**

[luaerror.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/2756190/luaerror.zip)

**Comment by emptyrivers** [comment] 2019-01-14 17:06
Related: when an author publishes an update which switches between a group and a standalone. The cause is different, but the error is the same.

This will be best served via a code change in WeakAuras, I think.

**Comment by Albrod** [comment] 2019-06-03 22:50
any news on this? im having the same issue

**Comment by mrbuds** [comment] 2022-03-12 13:24
Forgot to close this one, fixed with https://github.com/WeakAuras/WeakAuras2/issues/2637

**Closed by mrbuds** 2022-03-12 13:24 UTC
Labels: bug
