### ISSUE TITLE
Companion app is missing Weakauras.

### ISSUE THREAD

**Issue by ZaperActive** [WeakAuras/WeakAuras-Companion#88] opened 2019-01-29 13:38 UTC
**Operating System:**
- [X] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
1.1.3

**Companion App Console Log:**
//_Removed the big wall of useless html/javascript text_//
 
Console log tab only displays:
updaterHandler: update-not-available - undefined renderer.js:1 
Backup: weakauras-50584899#3-20190129022857.zip saved renderer.js:1 

**WeakAuras Version:**
 2.11.1

**WeakAuras Errors:**
None

**Describe the bug**
Companion App not showing all Weakauras, and thus not able to fetch all the new available updates.

Show auras without updates is ticked on.

I would like to say that I acknowledge that this app is new, and i bound to have a few bugs. I do hope the information i have provided can help.

**To Reproduce**
As showed in the linked screenshot of the Weakaura addon in-game, it is displaying Causese's  "T23 Battle of Dazar'alor" Aura. while in the Companion app it is missing. 

Tried removing and adding the missing Weakauras. Mainly Causese's  "T23 Battle of Dazar'alor" Aura. Still the same conclusion, the auras are missing in the companion app. 

**Expected behavior**
Expected all the in-game Weakauras to be loaded in the Companion app and updates being displayed when available. 

**Screenshots**
Screenshot is added in the zip file.

**Include a .zip file containing:**

Zip file included containing:
- Screenshot of the Weakaura addon in-game.
- Screenshot of the Companion app.
- WeakAuras.lua
- config.json

[Bug report  extra files.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/2807811/Bug.report.extra.files.zip)

**Comment by ZaperActive** [comment] 2019-01-29 15:02
Weird this is what i see in the companion app:
![2019-01-29 15_38_46-start](https://user-images.githubusercontent.com/47144772/51915872-5ce80e80-23dc-11e9-8b39-e95a28a42291.jpg)

Yeah I figured you only wanted the console tab, it just seemed so empty to even post, hence i added the whole html/javascript. It will not be included next time.

I have now tried uninstalling the Companion app again and completely removed all traces of the companion app in appdata, there were still some data files and old updates after the uninstall.
![2019-01-29 15_49_21-start](https://user-images.githubusercontent.com/47144772/51916820-6b372a00-23de-11e9-98cf-9176b14709b2.jpg)
![2019-01-29 15_49_09-start](https://user-images.githubusercontent.com/47144772/51916869-84d87180-23de-11e9-8869-1f464efaec56.jpg)
And now after a complete clean install, it seems to be working as it should.
![2019-01-29 15_58_41-start](https://user-images.githubusercontent.com/47144772/51916986-c79a4980-23de-11e9-8596-85922c41a184.jpg)

**Comment by mrbuds** [comment] 2019-01-29 15:05
Pressing the red button at the bottom of settings could have probably achieve same result.

But i can reproduce your issue using your config.json edited to use my account, still trying to figure it.

**Comment by ZaperActive** [comment] 2019-01-29 15:10
Shouldn't an uninstall at least remove the data part used by the companion app. or by a new install overwrite the old files?

**Comment by ZaperActive** [comment] 2019-01-29 15:25
Posting this here to possible help people with the same problem in the future.

**My problem has been fixed and the solution would be to first try the "Reset Settings and Data" under Settings in the Companion app. Else do a clean uninstall and remove all traces of the Weakaura companion app in Appdata, as there were still data files(ex. config.json) left after the uninstall.**

Thanks for the quick responses mrbud.

**Comment by mrbuds** [comment] 2019-01-29 15:50
No the problem is not fixed and reset settings is not a solution but a workaround.

It seems the deeper issue here is that you have a fat list of auras, and the api request with Wago is accessed with the GET method, and append a long concatenated list of auras "slugs" to the url.

https://data.wago.io/api/check/weakauras?ids=AmiYuy-Hunter-ActiveBuffs,bfaraid1,B1CddONSX,BJ6P_ONBX,rJg1u_VSX,HJii5HtQQ,VJdTRIH_b,N1ji6IBu-,EyZrCUrdW,ByQlgka_m,SygUVHZ5m,S1Q-LGIrQ,r1Kw4TB_X,HJIqbonOQ,HJ9nJ8__Q,HkaQp6XFQ,AmiYuy-Hunter-SVAbilities,rkALOdES7,B1Yzd9btm,AmiYuy-Hunter-BMAbilities,AmiYuy-Hunter-MMAbilities,rJ_qFVeBm,rkzIxo8Om,HJGLGXx9X,ry1Yd036X,Hk0AZj3_X,explosiveorbs,BJyKqIu_Q,BJDtLF7hX,BJbq_OVBm,BknGyoIuQ,Vy_cmLXaz,SJ-2C17FX,ryqpLw4pm,BJipkL_dX,AmiYuy-Hunter-FocusUse,rk3kVS-5X,B1NyC3S_Q,H1ZvVFCrQ,4Jm_C8SO-,B1pfxTOtb,FrenzyTracker,H1sA8dgDm,NkAOjKJ6G,BJKuoq0oX,SkjHi61Bz,HkUtqi7QQ,BkQog1SSm,HycNvglo7,BJkqW_85m,bfaraid2,dnSI1JGDv,rJ4gooXEZ,S1jg1ImqZ

Server response is missing data when url reach a size limit.

Solution will probably to make this API also accept POST request, i will discuss it with @oratory.

**Comment by ZaperActive** [comment] 2019-01-29 17:01
I see, I have edited it to say workaround instead. so the problem would be, that having too many weakauras would cause it to reach the string limit, resulting it not loading the last missing auras?

Anyway do you want me to keep the issue open until you get around to a possible fix. or should I close it?.

**Comment by mrbuds** [comment] 2019-01-29 17:01
I will close it when it's fixed

**Comment by mrbuds** [comment] 2019-02-01 20:46
wago api had a 50 aura limit per request, it has been raised to 200

**Closed by mrbuds** 2019-02-01 20:46 UTC
Labels: bug
