### ISSUE TITLE
Left + right click on topbar make companion follow your cursor💩

### ISSUE THREAD

**Issue by Vardex** [WeakAuras/WeakAuras-Companion#91] opened 2019-01-29 21:52 UTC
**Operating System:**
- [x] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
Check the bottom left of the "About" panel in the app.
```
1.1.3

**Companion App Console Log:**
```
Press Ctrl+Shift+I to open the console and copy-paste everything here
```
🙅

**WeakAuras Version:**
```
/run print(WeakAuras.versionString) in-game.
```
🙅

**WeakAuras Errors:**
```
1. Install https://mods.curse.com/addons/wow/BugSack
2. Install https://mods.curse.com/addons/wow/bug-grabber
3. Try to do whatever it is you're having a problem with again
4. Check your minimap for an icon that looks like a bag.  Is it green, or is it red?
   • GREEN
      • WeakAuras is working correctly.
      • Either you found a behavioral bug, or you are just doing it wrong :)
      • Explain the steps you took, and we will try to figure out what happened.
   • RED 
     • There are error messages. Click on the red bag to see them.
     • Copy & Paste here all of the error messages (there may be more than one, click the 'previous' button on the dialog to see previous ones
```
🙅

**Describe the bug**
When I left click and right click at the same time on the topbar of the companion it make it "sticky" and the companion follow my mouse cursor.

**To Reproduce**
1. Open Companion
2. Left and right click at the same time on the top bar

**Expected behavior**
🤷

**Screenshots**
🙅

**Include a .zip file containing:**
`%programfiles%\World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\WeakAuras.lua`
AND
`%appdata%\weakauras-companion\config.json`
🙅

**Comment by mrbuds** [comment] 2019-01-30 00:36
duplicate of #84

**Closed by mrbuds** 2019-01-30 00:36 UTC
Labels: bug
