### ISSUE TITLE
Minimize on close

### ISSUE THREAD

**Issue by derekschrock** [WeakAuras/WeakAuras-Companion#1938] opened 2023-06-15 02:33 UTC
**Operating System:**
- [x] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
5.0.1
```

**Describe the bug**
When closing the application via the close window X button, upper right of the window, would it be possible to have an option in settings, off by default, that would minimize the application to systray?

**To Reproduce**
1. Open application
2. Click close button
3. See the application is closed and is no longer in the systray.

**Expected behavior**
If the minimized on close setting is enabled and you close the application via the close window X button the application is minimized to the systray.  If you want to fully quit the application you would use the systrap right click to quit.

**Comment by mrbuds** [comment] 2023-06-15 08:24
duplicate of https://github.com/WeakAuras/WeakAuras-Companion/issues/1440

**Closed by mrbuds** 2023-06-15 08:24 UTC
Labels: bug
