### ISSUE TITLE
error in updater

### ISSUE THREAD

**Issue by luizofoca** [WeakAuras/WeakAuras-Companion#537] opened 2019-12-31 13:40 UTC
**Operating System:**
- [x] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
VERSION 2.0.0
```

**Companion App Console Log:**
```
Press Ctrl+Shift+I to open the console and copy-paste everything here (didn't open console)
```

![image](https://user-images.githubusercontent.com/36965683/71623314-5a78d080-2bba-11ea-8ecc-d9628023895f.png)

**Comment by mrbuds** [comment] 2019-12-31 13:49
Duplicate of https://github.com/WeakAuras/WeakAuras-Companion/issues/528
You can get last version at <https://github.com/WeakAuras/WeakAuras-Companion/releases>

**Closed by mrbuds** 2019-12-31 13:49 UTC
Labels: bug, duplicate
