### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by marcelmfa** [WeakAuras/WeakAuras-Companion#720] opened 2020-06-24 20:34 UTC
**Operating System:**
- [X] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
3.0.1

**Companion App Console Log:**
On UI shows error "Cant read Wago answer" "Error: Network error"
On console:
```
Uncaught (in promise) TypeError: Cannot read property 'apply' of undefined
    at VueI18n.extendedPluralRules [as getChoiceIndex] (main.js?b503:52)
    at VueI18n.getChoiceIndex (vue-i18n.esm.js?a925:1176)
    at VueI18n.fetchChoice (vue-i18n.esm.js?a925:1776)
    at VueI18n._tc (vue-i18n.esm.js?a925:1768)
    at VueComponent.Vue.$tc (vue-i18n.esm.js?a925:200)
    at VueComponent.afterUpdateNotification (LandingPage.vue?b116:1914)
    at VueComponent.writeAddonData (LandingPage.vue?b116:1878)
```

**WeakAuras Version:**
Latest

**WeakAuras Errors:**
No errors

**Describe the bug**
Updated the code locally, run app and try to get auras updates, resulting in error

**To Reproduce**
1. git pull
2. yarn
3. yarn dev
4. Fetch updates and see error described above

> I tried multiples terminal apps and run them as admin, suspecting of file permissions

**Expected behavior**
See auras updates or nothing to update.

**Screenshots**
https://snipboard.io/x5nfzQ.jpg

**Comment by mrbuds** [comment] 2020-06-24 23:33
I can reproduce an issue, but the error msg you gave seems unrelated

![image](https://user-images.githubusercontent.com/189656/85637312-2b33af80-b683-11ea-8e0c-155d1517ec2f.png)

client code : https://github.com/WeakAuras/WeakAuras-Companion/blob/master/src/components/LandingPage.vue#L900

on a related issue for axios https://github.com/axios/axios/issues/2345 someone give an advice to add headers server side
```
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");
header("Access-Control-Allow-Headers: Authorization");
```

I'm clueless about how CORS works, i suspect this error is due to a fix (or a bug ?) done in latest electron updates
Any though about it @oratory ?

**Comment by mrbuds** [comment] 2020-06-24 23:41
The packaged version using `yarn build` is working fine for me.

**Comment by oratory** [comment] 2020-06-25 00:39
Not sure why build would be different from dev, but it looks like the dev is now using the `Access-Control-Allow-Headers` response header. I added in `identifier` and `api-key` as allowed request headers on Wago, but you also have `Content-Security-Policy` as a request header, and this is only a response header. 

Basically if you were viewing a website and the response headers included that, then any remote request (be it files or ajax or whatever) could only be to the allowed domains. But it does nothing as an outgoing request header so that just needs to be removed from the app's $http requests. 

Instead you can add it as a meta tag `<meta http-equiv="Content-Security-Policy" content="script-src 'self' https://data.wago.io" />` and add additional allowed domains as necessary. This is useful in case of any included libraries the Companion is using is covertly malicious.

**Comment by emptyrivers** [comment] 2020-06-25 02:47
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSInvalidAllowHeader this is the relevant information about this particular CORS error.

**Comment by mrbuds** [comment] 2020-06-25 10:09
This is now fixed with https://github.com/WeakAuras/WeakAuras-Companion/commit/77886ca90515ce6dd74c412ae35087b841c77b37 and https://github.com/oratory/wago.io/commit/52c15b53064bd9984122e26de989aa5e9bdf6a1c

**Closed by mrbuds** 2020-06-25 10:09 UTC
Labels: bug
