### ISSUE TITLE
Add setting to allow exit button to minimize to system tray

### ISSUE THREAD

**Issue by lyledouglass** [WeakAuras/WeakAuras-Companion#1648] opened 2022-11-20 01:57 UTC
I've found myself accidentally clicking the exit button on windows and then not realizing the app has exited. It would be nice to have a checkbox like some other apps have (Wowup is an example I have in front of me) where the exit button just moves it to the system tray rather than exiting the app. 

Wowup example:
![image](https://user-images.githubusercontent.com/58087519/202879044-82b273da-0071-411f-8ae3-3c704d4a25ef.png)

Cheers!

**Comment by mrbuds** [comment] 2022-11-20 02:55
duplicate of https://github.com/WeakAuras/WeakAuras-Companion/issues/1440

**Closed by mrbuds** 2022-11-20 02:55 UTC
Labels: duplicate, wontfix
